language: node_js

stages:
  - lint
  - test
  - compile
  - name: deploy
    if: branch = master

cache:
  directories:
    - "node_modules"

install:
    - yarn install

jobs:
  include:
    - stage: build
      script:
        - yarn lint
        - yarn test
        - yarn build
    - stage: deploy
      script:
        - yarn global add vsce
        - vsce publish
