language: node_js

stages:
  - build
  - name: deploy
    if: branch = master AND type != pull_request

cache:
  directories:
    - "node_modules"

before_install:
  - npm install -g vsce

install:
  - yarn install

jobs:
  include:
    - stage: build
      script:
        - $(npm config get prefix)/bin/vsce --version
        - yarn lint
        - yarn test
        - yarn build
    - stage: deploy
      script:
        - $(npm config get prefix)/bin/vsce publish -p $AZURE_PAT
