language: node_js
node_js:
  - "8"

stages:
  - build
  - name: deploy
    if: branch = master AND type != pull_request

cache:
  directories:
    - "node_modules"

before_install:
  - npm install -g vsce

install:
  - npm install

jobs:
  include:
    - stage: build
      script:
        - $(npm config get prefix)/bin/vsce --version
        - npm run lint
        - npm run compile
    - stage: deploy
      script:
        - $(npm config get prefix)/bin/vsce publish -p $AZURE_PAT
