language: node_js

stages:
  - lint
  - test
  - compile
  - name: deploy
    if: branch = master

cache:
  directories:
    - "node_modules"

install:
    - yarn install

jobs:
  include:
    - stage: lint
      script:
        - yarn lint
    - stage: test
      script:
        - yarn test
    - stage: compile
      script:
        - yarn build
    - stage: deploy
      script:
        - yarn global add vsce
        - vsce publish
