language: node_js

stages:
  - lint
  - test
  - compile
  - name: deploy
    if: branch = master AND type != pull_request

cache:
  directories:
    - "node_modules"

before_install:
  - yarn global add vsce

install:
  - yarn install

jobs:
  include:
    - stage: build
      script:
        - vsce --version
        - yarn lint
        - yarn test
        - yarn build
    - stage: deploy
      script:
        - yarn deploy
