language: node_js

stages:
  - lint
  - test
  - compile
  - name: deploy
    if: branch = master AND type != pull_request

cache:
  directories:
    - "node_modules"

install:
  - npm install -g vsce
  - npm install

script:
  - npm run lint
  - vsce package

deploy:
  - provider: script  
    script: vsce publish -p $AZURE_PAT
    skip_cleanup: true
    on:
      branch: master
