language: node_js
node_js:
  - "8"

stages:
  - build
  - name: deploy
    if: branch = master AND type != pull_request

cache:
  directories:
    - "node_modules"

install:
  - npm install -g vsce
  - npm install

script:
  - npm run lint
  # npm ls command is broken causing vsce to fail, see:
  # https://github.com/Microsoft/vscode-vsce/issues/246
  - vsce package --yarn

deploy:
  - provider: script  
    script: vsce publish --yarn -p $AZURE_PAT
    skip_cleanup: true
    on:
      branch: master
